<?php
return array(
	'title' => 'Términos',
	'intro' => '<h3>De las condiciones</h3>',
	'main' => '<ul><li><b>Super Fiesta</b> es una empresa única, creada el 24 de Febrero de 2017 y registrada en Registro de Comercio bajo las leyes y estatutos fijados por la Confederación Suiza, con el fin de importación de bienes desde los Estados Unidos de América, desde la República Argentina, desde el Estado Plurinacional de Bolivia, desde la República Federativa del Brasil, desde la República de Chile, desde la República de Colombia, desde la República de Costa Rica, desde la República de Cuba,  desde la República Dominicana, desde la República del Ecuador, desde la República de El Salvador, desde el Reino de España, desde la República de Guatemala, desde la República de Haití, desde la República de Honduras, desde los Estados Unidos Méxicanos, desde la República de Nicaragua, desde la República de Panamá, desde la República del Paraguay, desde la República del Perú, desde la República Portuguesa, desde la República Oriental del Uruguay y desde la República Bolivariana de Venezuela.</li> 
<li> Los bienes importados y ofrecidos por <b>Super Fiesta</b> corresponden a alimentos, productos congelados, zapatos, vestidos y productos electrónicos, cuya venta se realiza por medio de la aplicación <b>Super Fiesta</b> para los usuarios de la misma. </li>
<li> La aplicación <b>Super Fiesta</b> (cuyo nombre corresponde a la empresa registrada) fue creada por el señor Oscar Ramírez Robayo mediánte programación HTML, CSS, SASS, VUE, PHP, Laravel, Bootstrap, C++, SQL, TexMaker, Photoshop CS6, rStudio, Ajax, JavaScript y disponible desde Marzo de 2017 a los usuarios de Internet para proporcionarles información y adquisición de los bienes y servicios ofrecidos por la empresa <b>Super Fiesta</b>.</li>
<li> La empresa <b>Super Fiesta</b> y la aplicación <b>Super Fiesta</b> definen usuario como persona identificable para convenio por escrito con la empresa <b>Super Fiesta</b> cuyo fin es la prestación del servicio de compra/venta de productos importados.</li>
<li> La empresa <b>Super Fiesta</b> define casos de fuerza mayor a los acontecimientos, que suceden a pesar de la falta de máxima precaución y son causados por el usuario o por terceros.</li>
<li> La empresa <b>Super Fiesta</b> define lugar de entrega al sitio a donde la entrega o suministro de productos de acuerdo con los términos y condiciones generales.</li>
<li> La empresa <b>Super Fiesta</b> define contrato como el acuerdo escrito entre personas identificables para la prestación del servicio mediante la aplicación <b>Super Fiesta</b>.</li>
<li> La empresa <b>Super Fiesta</b> define forma escrita como la forma de convenio entre personas identificables mediánte escritos, fax, correos electrónicos u otra forma.</li>
<li> La empresa <b>Super Fiesta</b> define prospectos y catálogos como indicaciones de informaciones con respecto a la oferta de productos mediante la aplicación <b>Super Fiesta</b>.</li>
<li> La empresa <b>Super Fiesta</b> define precios como el valor de obra del productor, del empaque, de la carga, de los seguros, de la exportación, del tránsito, de la importación, y otras autorizaciones que hagan parte de costos al usuario. El usuario debe contar con impuestos, cotizaciones, aranceles y aduanas. Los precios contienen impuesto de venta.</li>
<li> La empresa <b>Super Fiesta</b> define pago como el cumplimiento de cuantías o saldos pendientes por los bienes y servicios prestados por la empresa <b>Super Fiesta</b> y dados a conocer mediante la aplicación <b>Super Fiesta</b>.</li>
<li> La empresa <b>Super Fiesta</b> define SSL como la transacción de información de modo seguro. El protocolo SSL 
utiliza claves de cifrado para la codificación y decodificación. La tecnología SSL codifica la información durante la transacción de dinero por medio del Internet y permite la confidencialidad del usuario. Esta tecnología es usada hoy día por servicios como VISA y MasterCard.</li>',
	'product' => 'A los productos'
);